#!/usr/bin/env bash
cd bin/selenium

find . -not -name '.gitignore' -type f -exec rm -f {} +

platform_gecko='linux64'
platform_chrome='linux64'
[ `uname` == 'Darwin' ] && platform_gecko='macos' && platform_chrome='mac64'

[[ ! -z GH_TOKEN ]] && GH_TOKEN="$GH_TOKEN@"

TARFILE_GECKO=v0.19.0/geckodriver-v0.19.0-${platform_gecko}.tar.gz
ZIPFILE_CHROME=2.33/chromedriver_${platform_chrome}.zip
JARFILE_STANDALONE=3.6/selenium-server-standalone-3.6.0.jar

curl --silent -kL https://${GH_TOKEN}github.com/mozilla/geckodriver/releases/download/${TARFILE_GECKO} \
     | tar xz
curl --silent -kL https://chromedriver.storage.googleapis.com/${ZIPFILE_CHROME} \
     -o tmp && unzip tmp && rm tmp
curl --silent -kL https://selenium-release.storage.googleapis.com/${JARFILE_STANDALONE} \
     -o selenium-server-standalone.jar
